controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 0.5
      base_joint:
        trajectory: 1.0
        goal: 0.5
      shoulder_joint:
        trajectory: 1.0
        goal: 0.5
      elbow_joint:
        trajectory: 1.0
        goal: 0.5
      wrist_pitch_joint:
        trajectory: 1.0
        goal: 0.5
      wrist_roll_joint:
        trajectory: 1.0
        goal: 0.5
    gains:
      base_joint:      {p: 10000.0, i: 1.0, d: 10.0, i_clamp: 1.0}
      shoulder_joint:  {p: 10000.0, i: 1.0, d: 10.0, i_clamp: 1.0}
      elbow_joint:     {p: 10000.0, i: 1.0, d: 10.0, i_clamp: 1.0}
      wrist_pitch_joint: {p: 10000.0, i: 1.0, d: 10.0, i_clamp: 1.0}
      wrist_roll_joint: {p: 10000.0, i: 1.0, d: 10.0, i_clamp: 1.0}

gripper_controller:
  ros__parameters:
    joints:
      - gripper_joint
      - sub_gripper_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 0.5
      gripper_joint:
        trajectory: 1.0
        goal: 0.5
      sub_gripper_joint:
        trajectory: 1.0
        goal: 0.5
    gains:
      gripper_joint:     {p: 100.0, i: 1.0, d: 0.1, i_clamp: 1.0}
      sub_gripper_joint: {p: 100.0, i: 1.0, d: 0.1, i_clamp: 1.0}
